Update package.yml

diff --git a/.github/workflows/package.yml b/.github/workflows/package.yml
--- a/.github/workflows/package.yml
+++ b/.github/workflows/package.yml
@@ -38,10 +38,21 @@ jobs:
     - name: Package with PyInstaller
       run: |
         pyinstaller --onefile --add-data "static;static" signapp.py
+
+    - name: List Dist Directory
+      run: |
         dir dist
 
-    - name: Upload the package
+    - name: Verify and Upload the package
+      if: success()
+      run: |
+        if [ -f "dist/signapp.exe" ]; then
+          echo "Executable created successfully."
+        else
+          echo "Executable not found!"
+          exit 1
+        fi
       uses: actions/upload-artifact@v2
       with:
         name: packaged-app
-        path: dist/app.exe
+        path: dist/signapp.exe
